$primary_paletteKeyColor = 8c6aa2
$secondary_paletteKeyColor = 817287
$tertiary_paletteKeyColor = 9d6a6c
$neutral_paletteKeyColor = 7b757c
$neutral_variant_paletteKeyColor = 7c747e
$background = 060406
$onBackground = e9e0e8
$surface = 060406
$surfaceDim = 060406
$surfaceBright = 111012
$surfaceContainerLowest = 040305
$surfaceContainerLow = 09070a
$surfaceContainer = 0a080b
$surfaceContainerHigh = 0e0b0e
$surfaceContainerHighest = 100f11
$onSurface = e9e0e8
$surfaceVariant = 151315
$onSurfaceVariant = cdc3ce
$inverseSurface = e9e0e8
$inverseOnSurface = 332f35
$outline = 978e98
$outlineVariant = 4b454d
$shadow = 000000
$scrim = 000000
$surfaceTint = 32213d
$primary = dfb8f6
$onPrimary = 412356
$primaryContainer = 593a6e
$onPrimaryContainer = f3daff
$inversePrimary = 725188
$secondary = d2c1d9
$onSecondary = 382c3e
$secondaryContainer = 4f4256
$onSecondaryContainer = efdcf5
$tertiary = f4b7b9
$onTertiary = 4c2528
$tertiaryContainer = b98385
$onTertiaryContainer = 000000
$error = ffb4ab
$onError = 690005
$errorContainer = 93000a
$onErrorContainer = ffdad6
$primaryFixed = f3daff
$primaryFixedDim = dfb8f6
$onPrimaryFixed = 2b0c40
$onPrimaryFixedVariant = 593a6e
$secondaryFixed = efdcf5
$secondaryFixedDim = d2c1d9
$onSecondaryFixed = 221729
$onSecondaryFixedVariant = 4f4256
$tertiaryFixed = ffdada
$tertiaryFixedDim = f4b7b9
$onTertiaryFixed = 331014
$onTertiaryFixedVariant = 663b3d
$term0 = 080808
$term1 = e34df5
$term2 = ffbac2
$term3 = ffdcf2
$term4 = aca4d7
$term5 = cd97db
$term6 = 9dceff
$term7 = e8d3de
$term8 = ae9ea7
$term9 = f476ff
$term10 = ffd2d5
$term11 = fff0f6
$term12 = babfdd
$term13 = e0aee7
$term14 = bae0ff
$term15 = ffffff
$rosewater = fbeef6
$flamingo = f1dbee
$pink = f4d1ff
$mauve = dcaefe
$red = de9dea
$maroon = ddb0e1
$peach = f3bdea
$yellow = ffecf3
$green = c8e3ff
$teal = dedcff
$sky = ded6ff
$sapphire = cebeff
$blue = cdaeff
$lavender = dec1ff
$klink = 9379cc
$klinkSelection = 9379cc
$kvisited = a367c8
$kvisitedSelection = a367c8
$knegative = c958db
$knegativeSelection = c958db
$kneutral = f67cf0
$kneutralSelection = f67cf0
$kpositive = 60adff
$kpositiveSelection = 60adff
$text = e9e0e8
$subtext1 = cdc3ce
$subtext0 = 978e98
$overlay2 = 1c1c1c
$overlay1 = 191919
$overlay0 = 171516
$surface2 = 131213
$surface1 = 0f0d0f
$surface0 = 080608
$base = 010001
$mantle = 010001
$crust = 010001
$success = B5CCBA
$onSuccess = 213528
$successContainer = 374B3E
$onSuccessContainer = D1E9D6
