$primary_paletteKeyColor = 5e8046
$secondary_paletteKeyColor = 6e7b62
$tertiary_paletteKeyColor = 517f7e
$neutral_paletteKeyColor = 75786f
$neutral_variant_paletteKeyColor = 74796d
$background = f9faef
$onBackground = 191d16
$surface = f9faef
$surfaceDim = d9dbd1
$surfaceBright = f9faef
$surfaceContainerLowest = ffffff
$surfaceContainerLow = f3f5ea
$surfaceContainer = edefe4
$surfaceContainerHigh = e7e9df
$surfaceContainerHighest = e1e4d9
$onSurface = 191d16
$surfaceVariant = e0e4d6
$onSurfaceVariant = 44483e
$inverseSurface = 2e312a
$inverseOnSurface = f0f2e7
$outline = 71766a
$outlineVariant = c4c8bb
$shadow = 000000
$scrim = 000000
$surfaceTint = 476730
$primary = 476730
$onPrimary = ffffff
$primaryContainer = c8eea8
$onPrimaryContainer = 304f1a
$inversePrimary = acd28f
$secondary = 56624b
$onSecondary = ffffff
$secondaryContainer = d7e4c7
$onSecondaryContainer = 3f4a35
$tertiary = 4f7c7c
$onTertiary = ffffff
$tertiaryContainer = 4f7c7c
$onTertiaryContainer = ffffff
$error = ba1a1a
$onError = ffffff
$errorContainer = ffdad6
$onErrorContainer = 93000a
$primaryFixed = c8eea8
$primaryFixedDim = acd28f
$onPrimaryFixed = 0a2000
$onPrimaryFixedVariant = 304f1a
$secondaryFixed = dae7ca
$secondaryFixedDim = becbaf
$onSecondaryFixed = 141e0c
$onSecondaryFixedVariant = 3f4a35
$tertiaryFixed = bbecea
$tertiaryFixedDim = a0cfce
$onTertiaryFixed = 002020
$onTertiaryFixedVariant = 1e4e4d
$term0 = 9b9b96
$term1 = 686300
$term2 = 5a8d35
$term3 = 6a7614
$term4 = 76933d
$term5 = 8b6300
$term6 = 4f8d58
$term7 = 1f2323
$term8 = 0f0f0f
$term9 = 817b00
$term10 = 79af52
$term11 = 869230
$term12 = 97b65c
$term13 = ac7b00
$term14 = 6faf76
$term15 = 25292a
$rosewater = 7c8239
$flamingo = 777a14
$pink = a37500
$mauve = 005e65
$red = 565800
$maroon = 676a00
$peach = 707c00
$yellow = 6f8714
$green = 357f00
$teal = 387541
$sky = 008c4f
$sapphire = 39814b
$blue = 00664e
$lavender = 00816c
$klink = 3d9764
$klinkSelection = 3d9764
$kvisited = c06b00
$kvisitedSelection = c06b00
$knegative = 8b8d00
$knegativeSelection = 8b8d00
$kneutral = a0b500
$kneutralSelection = a0b500
$kpositive = 6ebc51
$kpositiveSelection = 6ebc51
$text = 191d16
$subtext1 = 44483e
$subtext0 = 71766a
$overlay2 = 81867a
$overlay1 = 94988c
$overlay0 = a6a99d
$surface2 = b8bbb0
$surface1 = cccfc3
$surface0 = e3e4d9
$base = f9faef
$mantle = f1f1e8
$crust = ebece3
$success = 4F6354
$onSuccess = FFFFFF
$successContainer = D1E8D5
$onSuccessContainer = 0C1F13
