# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
# See https://wiki.hyprland.org/Configuring/Workspace-Rules/ for workspace rules
 
windowrule {
    name = kitty
    match:class = kitty
    float = on
    center = on
}
windowrule {
    name = blueman-manager
    match:class = blueman-manager
    size = 800 400
    center = on
    float = on
}
windowrule {
    name = Code
    match:class = Code
    opacity = 0.92 override
}
windowrule {
    name = Pavucontrol
    match:class = org.pulseaudio.pavucontrol
    float = on
    size = 800 400
    move = 300 50
}
windowrule {
    name = Clipse
    match:class = clipse
    float = on
    size = 550 550
    center = on
}
windowrule {
    name = Waypaper
    match:class = waypaper
    float = on
    center = on
}
windowrule {
    name = Calculator
    match:class = org.kde.kcalc
    float = on
    center = on
}
windowrule {
    name = File-Explorer
    match:class = org.gnome.Nautilus
    float = on
    center = on
}
windowrule {
    name = Picture-In-Picture
    match:title = Picture-in-Picture
    float = on
    pin = on
    move = 900 500
}

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
    name = windowrule-1
    suppress_event = maximize
    match:class = .*
    decorate = off
}

# Fix some dragging issues with XWayland
windowrule {
    name = windowrule-2
    no_focus = on
    match:class = ^$
    match:title = ^$
    match:xwayland = 1
    match:float = 1
    match:fullscreen = 0
    match:pin = 0
}
