windowrule {
  name = Kitty
  match:class = kitty
  float = on
  size = 610 600
  center = on
}
# Bluetooth
# windowrule {
#   name = windowrule-2
#   match:class = blueman-manager
#   float = on
#   size = 500 200
#   move = 820 50
#   opacity = 0.8 override
# }

windowrule {
  name = Pulseaudio
  match:class = org.pulseaudio.pavucontrol
  float = on
  size = 800 400
  move = 1000 50
}

windowrule {
  name = Clipse
  match:class = clipse
  float = on
  size = 622 652
  move = 650 100
}

windowrule {
  name = Waypaper
  match:class = waypaper
  float = on
  size = 1024 661
  center = on
}

windowrule {
  name = Calculiadora
  float = on
  match:class = ^(org.kde.kcalc)$
}

windowrule {
  name = File-Explorer
  match:class = org.gnome.Nautilus
  float = on
  size = 940 654
  center = on
}

windowrule {
  name = Code
  match:class = code
  opacity = 0.92 override
}
windowrule {
  name = Code-Folder
  match:initial_title = Open Folder
  float = on
  size = 800 600
  center = on
}
windowrule {
  name = Code-Save
  match:initial_title = Save As
  float = on
  size = 800 600
  center = on
}
windowrule {
  name = Code-File
  match:initial_title = Open File
  float = on
  size = 800 600
  center = on
}

windowrule {
  name = Picture-In-Picture
  match:title = Picture-in-Picture
  float = on
  size = 404 281
  move = 1496 719
  pin = on
}

windowrule {
  name = Piper
  match:class = piper
  float = on
  size = 1012 641
  center = on
}

windowrule {
  name = windowrule-16
  match:class = net.davidotek.pupgui2
  float = on
  center = on
}

windowrule {
  name = Displays
  match:class = nwg-displays
  float = on
  size = 1184 821
  center = on
}

# Emulator PCSX2
windowrule {
  name = PCSX2-Controller
  match:initial_title = PCSX2 Controller Settings
  float = on
  center = on
  size = 1308 710
}
windowrule {
  name = PCSX2-Settings
  match:initial_title = Ajustes de PCSX2
  float = on
  center = on
  size = 954 728
}

windowrule {
  name = Bluetooth
  match:initial_class = blueman-manager
  float = on
  center = on
  size = 896 433
}

# Steam
windowrule {
  name = Steam-Friends
  match:initial_title = Friends List
  float = on
  size = 434 639
  move = 70 60
}
windowrule {
  name = Steam-Settings
  match:initial_title = Steam Settings
  float = on
  size = 850 722
  center = on
}
# Obsidian
windowrule {
  name = Obsidian
  match:class = obsidian
  float = on
  size = 850 722
  center = on
}

windowrule {
  name = Code-Folder
  match:initial_title = Open Folder
  float = on
  size = 800 600
  center = on
}
windowrule {
  name = Code-Save
  match:initial_title = Save As
  float = on
  size = 800 600
  center = on
}
windowrule {
  name = Code-File
  match:initial_title = Open File
  float = on
  size = 800 600
  center = on
}
windowrule {
  name = Codium
  match:class = codium
  opacity = 0.97 override
}

windowrule {
  name = zencal
  float = on
  size = 14% 18%
  move = 86% 2.5%
}

# Ignore maximize requests from apps. You'll probably like this.
windowrule {
  name = windowrule-13
  suppress_event = maximize
  match:class = .*
  decorate = off
}


# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-14
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}
